let firstName = 'Barry';
let lastName = 'Percy';
let middleName = 'Dale';
let fullName = '';
fullName = firstName + ' ' + middleName + ' ' + lastName;
console.log('hello, my name is', fullName);
let myAge = 29;
let currentYear = 2022;
let myBirthYear = currentYear - myAge;
console.log('My age is', myAge,'. My birth year is', myBirthYear);